### ISSUE TITLE
Define name mangling for double-underscore names

### ISSUE THREAD

**Issue by scoder** [cython/cython#3544]
This is a follow-up to #1382 and #3123.

Python mangles double-underscore names inside of class bodies and methods:
```python
  >>> class T:
  ...   def f(self): return __xyz
  ...
  >>> __xyz = 2
  >>> T().f()
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "<stdin>", line 2, in f
  NameError: name '_T__xyz' is not defined
```
However, double-underscore names are not uncommon in C APIs, which conflicts with the semantics of Python's name mangling.

Proposal:
- mangle names according to Python rules
- on compile-time lookups, if a mangled name is not found, look up the non-mangled (plain) name
- if a plain name is found, assume the reference refers to that
- otherwise, assume that the mangled name will become available at runtime.

Optional:
- exclude global Python (module dict, non-cdef) names from the plain name lookup (would that inconsistency be surprising for users?)

This issue was originally raised [on the mailing list](https://mail.python.org/pipermail/cython-devel/2020-April/005340.html).

**Comment by da-woods** [comment]
> otherwise, assume that the mangled name will become available at runtime.

if [`error_on_unknown_names`](https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#Cython.Compiler.Options.error_on_unknown_names) would normally allow it?

> exclude global Python names from the plain name lookup (would that inconsistency be surprising for users?)

I'm a little undecided about this. I'm also not 100% sure if we have the information to do this or not (and that may end up deciding it anyway). Just to clarify, my idea was that it's the `cdef` definition that decides this, not whether an object is a PyObject.

The advantage would be that it maximizes Python compatibility. It does seem potentially confusing, and I'd definitely give a warning where possible.

Other than that this seems like a good solution.

**Comment by scoder** [comment]
I guess `error_on_unknown_names` is rarely disabled by users, but yeah, it seems related enough to look at it as well. Although, I guess we already do that at this point. I'm not sure anything would change there. I wouldn't want to require users to disable this option in order to make this fallback lookup work.

I'd say, let's only include `cdef` declarations for now (excluding `is_pyglobal` module level names and builtins), since that's the main concern here. If we find that it's confusing to users, we can open it up to Python dict globals, but it would be more difficult to close it down later than to open it up.

**Comment by Gelbpunkt** [comment]
I've had the same issue when compiling uvloop (https://github.com/MagicStack/uvloop) with the cython master branch, it threw tons of errors related to undefined variables, but compiled fine against 0.29.16.

With #3546, it got better and only throws two errors now:
```py
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-8ak75u3u/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-8ak75u3u/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-8ak75u3u/pip-egg-info
         cwd: /tmp/pip-req-build-8ak75u3u/
    Complete output (57 lines):
    running egg_info
    creating /tmp/pip-req-build-8ak75u3u/pip-egg-info/uvloop.egg-info
    writing /tmp/pip-req-build-8ak75u3u/pip-egg-info/uvloop.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-req-build-8ak75u3u/pip-egg-info/uvloop.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-req-build-8ak75u3u/pip-egg-info/uvloop.egg-info/top_level.txt
    writing manifest file '/tmp/pip-req-build-8ak75u3u/pip-egg-info/uvloop.egg-info/SOURCES.txt'
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                            os_set_inheritable(fd, True)
            except Exception:
                self._abort_init()
                raise
    
            if __forking or loop.active_process_handler is not None:
              ^
    ------------------------------------------------------------
    
    uvloop/handles/process.pyx:62:11: local variable '_UVProcess__forking' referenced before assignment
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-8ak75u3u/setup.py", line 234, in <module>
        setup(
      File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 297, in run
        self.find_sources()
      File "/usr/local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 304, in find_sources
        mm.run()
      File "/usr/local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 535, in run
        self.add_defaults()
      File "/usr/local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 571, in add_defaults
        sdist.add_defaults(self)
      File "/usr/local/lib/python3.9/distutils/command/sdist.py", line 228, in add_defaults
        self._add_defaults_ext()
      File "/usr/local/lib/python3.9/distutils/command/sdist.py", line 311, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "/usr/local/lib/python3.9/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/local/lib/python3.9/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/tmp/pip-req-build-8ak75u3u/setup.py", line 145, in finalize_options
        self.distribution.ext_modules[:] = cythonize(
      File "/usr/local/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1105, in cythonize
        cythonize_one(*args)
      File "/usr/local/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1263, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: uvloop/loop.pyx
    Compiling uvloop/loop.pyx because it changed.
    [1/1] Cythonizing uvloop/loop.pyx
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Is there any chance that this can be fixed, too?

**Comment by da-woods** [comment]
@Gelbpunkt I think your remaining bug is from the deliberate decision that: "Python globals shouldn't be found because that contradicts Python's name lookup rules". This decision may still change....

It should work if you define `__forking` (and the other variables as needed) with `cdef` at the module level:

    cdef __forking

It'd be useful to know if that fix works (even if we change our minds about that the rule that leads us there)?

**Comment by scoder** [comment]
https://github.com/MagicStack/uvloop/blob/2870219558eba983813aeab249e08371266ab524/uvloop/handles/process.pyx#L29

Yes, it's a global Python variable, and thus falls under Python semantics in the currently discussed state of affairs. However, I wonder why it wasn't defined as `cdef bint __forking` in the first place. A Python variable seems unnecessarily inefficient here. Maybe it's meant to be visible for debugging purposes?

**Comment by scoder** [comment]
Anyway – given that we clearly break code here without a strict necessity, I now think we should take the time for a proper deprecation cycle and warn about the Python name case first in 3.0, while keeping a lookup fallback for _all_ names, and then (maybe) switch to full Python semantics for Python names later. The main goal should be to prevent newly written code from depending on the old behaviour and allowing existing code to adapt, so a warning is better than breakage.

**Comment by Gelbpunkt** [comment]
@da-woods Good tip - I tried! I am not a C expert at all, but it seems that the variable is declared already:

```py
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    include "server.pyx"
    
    
    # Used in UVProcess
    cdef vint __atfork_installed = 0
    cdef vint __forking = 0
             ^
    ------------------------------------------------------------
    
    uvloop/loop.pyx:3205:10: '__forking' redeclared
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    cdef __forking
                 ^
    ------------------------------------------------------------
    
    uvloop/handles/process.pyx:1:14: Previous declaration is here
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                            os_set_inheritable(fd, True)
            except Exception:
                self._abort_init()
                raise
    
            if __forking or loop.active_process_handler is not None:
              ^
    ------------------------------------------------------------
    
    uvloop/handles/process.pyx:64:11: local variable '_UVProcess__forking' referenced before assignment
```

**Comment by da-woods** [comment]
Right - I've pushed an update so Python variables should be matched (but with a warning).

I'm slightly puzzled about your multiple definitions right now (but haven't really looked at it yet). See if the update works on the original code

**Comment by Gelbpunkt** [comment]
The original code with the update produces the same error as before.

**Comment by da-woods** [comment]
@Gelbpunkt Even more puzzled about your code now. I don't think "include .pyx files into one big .pyx file where certain key definitions are outside the include" is a good structure. However, it does look like `__forking` was defined as `cdef` in the first place so should have been found. Unless you're building "process.pyx" both on its own and and as part of "loop.pyx" (please tell me you're not!)?

Hopefully the updated PR fixes this and we don't have to investigate further...

**Comment by Gelbpunkt** [comment]
I'm not the author of uvloop - I'm just building a wheel from source with `pip wheel .` in the source directory. If you have cython installed, you should be able to reproduce it:
```sh
git clone https://github.com/MagicStack/uvloop
cd uvloop
git submodule update --init --recursive
pip wheel .
```
The updated PR does not fix the issue for me.

**Comment by scoder** [comment]
> include .pyx files into one big .pyx file

Yeah, the conventional file extension for include files would be `.pxi`, not `.pyx`. It's just a convention, though, so unless someone is really trying to build the include files separately as modules, it should not make a difference. Cython's parser will only see the complete resulting main .pyx file in the end, not the separate include files.

**Comment by da-woods** [comment]
Right - I think what's happening is that `global __forking` is being interpreted as "I promise there is a global variable called `_UVProcess__forking` (i.e. the mangled name) available". At his stage it doesn't check if there's actually a match to the name.

**Comment by scoder** [comment]
The code order might make a difference here. If the `global` is used before the `cdef` declaration has been seen, then it would declare a global object variable for the time being. Maybe we could extend the `ForwardDeclareTypes` pipeline stage to include `cdef` variable declarations as well, i.e. basically all static declarations?

**Comment by scoder** [comment]
OTOH, variables should be declared in code order. That's less of an issue for extension types (where the opposite is a problem due to forward references, inheritance, etc.). Hmm…

**Comment by da-woods** [comment]
Updated my PR.

@Gelbpunkt this definitely fixes uvloop (I've tested it on that specifically). Thanks for pointing it out - there was a useful slightly obscure case hidden in there.

**Comment by da-woods** [comment]
One further design question - should we be stricter about this in pure Python mode? Given .py files will normally have been written to work in Python too, it might be worth actually enforcing the original behaviour there?

**Comment by Gelbpunkt** [comment]
@da-woods thanks a lot! Compiles perfectly fine now - you are a lifesaver :smile:

**Comment by scoder** [comment]
I've merged #3548 as a fix. I'll close this ticket for now, assuming that we solved the issue in a good way. Please add comments if there are still problems with the new behaviour.
